### ISSUE TITLE
Tarea 032: Entidad Causes

### ISSUE THREAD

**Issue by marsamber** [gii-is-psg2/psg2-2122-g4-42#42]
Como cliente, podemos crear una causa que contenga un nombre y una descripción (string), un objetivo de presupuesto (double) y una organización sin fines de lucro activa (string) que usará el presupuesto para la causa.

Revisa: diegonqui

**Comment by pabsanper** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/psg2-2122-g4-42-623308a4186c100016aa5edf/issues/gii-is-psg2/psg2-2122-g4-42/42?planning-poker) with ZenHub @marsamber @marsannar2 @pabparmen

**Comment by pabsanper** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/psg2-2122-g4-42-623308a4186c100016aa5edf/issues/gii-is-psg2/psg2-2122-g4-42/42?planning-poker) with ZenHub @diegonqui
