### ISSUE TITLE
Tarea 035: Página de detalles de las causas

### ISSUE THREAD

**Issue by marsamber** [gii-is-psg2/psg2-2122-g4-42#45]
La página de detalles de las causas mostrará toda la información sobre la causa incluyendo los detalles de cada donación (fecha de la donación, cantidad y cliente). La página de detalles de las causas incluye un botón de donación que mostrará un formulario para realizar las donaciones.

Revisa: pabsanper

**Comment by pabsanper** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/psg2-2122-g4-42-623308a4186c100016aa5edf/issues/gii-is-psg2/psg2-2122-g4-42/45?planning-poker) with ZenHub @diegonqui @marsamber @marsannar2 @pabparmen
