### ISSUE TITLE
Tarea 036: Validación en las reservas del hotel

### ISSUE THREAD

**Issue by marsamber** [gii-is-psg2/psg2-2122-g4-42#46]
Implemente una funcionalidad de validación en la creación de reservas de su hotel para mascotas que asegure que no hay reservas simultáneas en el hotel para la misma mascota. 

Revisa: marsannar2

**Comment by pabsanper** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/psg2-2122-g4-42-623308a4186c100016aa5edf/issues/gii-is-psg2/psg2-2122-g4-42/46?planning-poker) with ZenHub @diegonqui @marsamber @marsannar2 @pabparmen
