### ISSUE TITLE
Tarea 037: Entidad Adoption

### ISSUE THREAD

**Issue by marsamber** [gii-is-psg2/psg2-2122-g4-42#47]
Cree una funcionalidad de adopciones. Como propietario, podemos crear una solicitud de adopción cuando no podamos cuidar de nuestra mascota. 

Revisa: marsamber

**Comment by pabsanper** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/psg2-2122-g4-42-623308a4186c100016aa5edf/issues/gii-is-psg2/psg2-2122-g4-42/47?planning-poker) with ZenHub @diegonqui @marsamber @marsannar2 @pabparmen
