### ISSUE TITLE
Tarea 038: Solicitud y adopción mascota

### ISSUE THREAD

**Issue by marsamber** [gii-is-psg2/psg2-2122-g4-42#48]
Otros propietarios podrían enumerar las mascotas disponibles para adopción y presentar una solicitud (las solicitudes de adopción tendrán una descripción de cómo el solicitante cuidará de la mascota). Si el dueño original aprueba la solicitud, la mascota será transferida al solicitante y él/ella será el nuevo dueño de la mascota.

Revisa: pabparmen

**Comment by pabsanper** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/psg2-2122-g4-42-623308a4186c100016aa5edf/issues/gii-is-psg2/psg2-2122-g4-42/48?planning-poker) with ZenHub @diegonqui @marsamber @marsannar2 @pabparmen
