### ISSUE TITLE
Tarea 039: Hacer release tras los cambios

### ISSUE THREAD

**Issue by marsamber** [gii-is-psg2/psg2-2122-g4-42#49]
En grupo, una vez realizados los cambios anteriores, preparar una versión del proyecto Petclinic, creando una rama de versión correspondiente. En esta rama de lanzamiento, todos los miembros del grupo deben eliminar cualquier error y advertencia que esté presente en todos los archivos fuente del código desarrollado, hasta el momento en que se inicie el lanzamiento. Como resultado final de ese lanzamiento, la aplicación Petclinic actualizada debe implementarse en Heroku, bajo la misma URL que en el Sprint anterior, es decir, https://psg2-2122-gx-xy.herokuapp.com/, donde X- XY corresponde a la identificación del grupo.

**Comment by pabsanper** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/psg2-2122-g4-42-623308a4186c100016aa5edf/issues/gii-is-psg2/psg2-2122-g4-42/49?planning-poker) with ZenHub @diegonqui @marsamber @marsannar2 @pabparmen
