### ISSUE TITLE
Tarea 041: Métricas de Proceso Ágil y Recursos - Sprint 3

### ISSUE THREAD

**Issue by marsamber** [gii-is-psg2/psg2-2122-g4-42#51]
Para Sprint S3: 
- BurnDown chart,
- gráfico de control que muestra el tiempo de entrega,
- gráfico de control que muestra el tiempo del ciclo,
- puntos de historia totales entregados,
- porcentaje de puntos de historia entregados,
- calendario Niko-niko con un análisis cualitativo de su contenido (conclusiones y posibles acciones para mejorar la moral del equipo).

**Comment by pabsanper** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/psg2-2122-g4-42-623308a4186c100016aa5edf/issues/gii-is-psg2/psg2-2122-g4-42/51?planning-poker) with ZenHub @diegonqui @marsamber @marsannar2 @pabparmen
