### ISSUE TITLE
Tarea 042: Análisis del Código Fuente y Métricas Asociadas - Tarea a

### ISSUE THREAD

**Issue by marsamber** [gii-is-psg2/psg2-2122-g4-42#52]
Una captura de pantalla del panel de Sonar Cloud para el análisis de su proyecto y una descripción de las métricas proporcionadas en el panel y sus valores.

**Comment by pabsanper** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/psg2-2122-g4-42-623308a4186c100016aa5edf/issues/gii-is-psg2/psg2-2122-g4-42/52?planning-poker) with ZenHub @diegonqui @marsamber @marsannar2 @pabparmen
