### ISSUE TITLE
Tarea 043: Análisis del Código Fuente y Métricas Asociadas - Tarea b

### ISSUE THREAD

**Issue by marsamber** [gii-is-psg2/psg2-2122-g4-42#53]
Descripción y análisis de los posibles errores encontrados en el repositorio (en la sección de confiabilidad, en las medidas)

**Comment by pabsanper** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/psg2-2122-g4-42-623308a4186c100016aa5edf/issues/gii-is-psg2/psg2-2122-g4-42/53?planning-poker) with ZenHub @diegonqui @marsamber @marsannar2 @pabparmen
