### ISSUE TITLE
Tarea 044: Análisis del Código Fuente y Métricas Asociada - Tarea c

### ISSUE THREAD

**Issue by marsamber** [gii-is-psg2/psg2-2122-g4-42#54]
Descripción y análisis de los diferentes tipos de olores de código encontrados en los análisis (en el apartado de mantenibilidad, sobre medidas). Para cada tipo de código olor, el informe debe describir.
- El nombre y la descripción del olor del código
- Las diferentes causas del olor en su base de código
- Una evaluación justificada de la gravedad del olor del código
- Una breve descripción de cómo solucionarlo dependiendo de las causas

**Comment by pabsanper** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/psg2-2122-g4-42-623308a4186c100016aa5edf/issues/gii-is-psg2/psg2-2122-g4-42/54?planning-poker) with ZenHub @diegonqui @marsamber @marsannar2 @pabparmen
