### ISSUE TITLE
Tarea 045: Análisis del Código Fuente y Métricas Asociadas - Tarea d

### ISSUE THREAD

**Issue by marsamber** [gii-is-psg2/psg2-2122-g4-42#55]
Conclusiones sobre los resultados de los análisis.

**Comment by pabsanper** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/psg2-2122-g4-42-623308a4186c100016aa5edf/issues/gii-is-psg2/psg2-2122-g4-42/55?planning-poker) with ZenHub @diegonqui @marsamber @marsannar2 @pabparmen
