### ISSUE TITLE
Tarea 046: Actas

### ISSUE THREAD

**Issue by marsamber** [gii-is-psg2/psg2-2122-g4-42#56]
Trabajo en equipo a lo largo del sprint, reuniones diarias y apego a su definición de "Hecho".

**Comment by pabsanper** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/psg2-2122-g4-42-623308a4186c100016aa5edf/issues/gii-is-psg2/psg2-2122-g4-42/56?planning-poker) with ZenHub @diegonqui @marsamber @marsannar2 @pabparmen
