### ISSUE TITLE
Tarea 047: Sprint Planning

### ISSUE THREAD

**Issue by marsamber** [gii-is-psg2/psg2-2122-g4-42#57]
Sprint planning, gestión de tareas y cumplimiento de sus estimaciones iniciales y metodología interna.

**Comment by pabsanper** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/psg2-2122-g4-42-623308a4186c100016aa5edf/issues/gii-is-psg2/psg2-2122-g4-42/57?planning-poker) with ZenHub @diegonqui @marsamber @marsannar2 @pabparmen
