### ISSUE TITLE
Tarea 049: Sprint Retrospective

### ISSUE THREAD

**Issue by marsamber** [gii-is-psg2/psg2-2122-g4-42#59]
Retrospectiva del Sprint realizada, análisis del Sprint 3 incluyendo la aplicación del plan de acción definido en la retrospectiva del Sprint 2 y plan de acción para mejorar el trabajo en equipo para el Sprint 4.

**Comment by pabsanper** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/psg2-2122-g4-42-623308a4186c100016aa5edf/issues/gii-is-psg2/psg2-2122-g4-42/59?planning-poker) with ZenHub @diegonqui @marsamber @marsannar2 @pabparmen
