### ISSUE TITLE
Tarea 050 (EXTRA): Extender documentación

### ISSUE THREAD

**Issue by marsamber** [gii-is-psg2/psg2-2122-g4-42#60]
Como grupo, extienda los informes técnicos creados como resultado de A3.6 y A3.7 para analizar también las diferencias entre los resultados de las métricas y el análisis en S2 y S3. El documento también debe incluir una discusión sobre las causas de tales diferencias.

**Comment by pabsanper** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/psg2-2122-g4-42-623308a4186c100016aa5edf/issues/gii-is-psg2/psg2-2122-g4-42/60?planning-poker) with ZenHub @diegonqui @marsamber @marsannar2 @pabparmen
