### ISSUE TITLE
Tarea 051 (EXTRA): Implementar cambios de los malos olores

### ISSUE THREAD

**Issue by marsamber** [gii-is-psg2/psg2-2122-g4-42#61]
En grupo, amplíen el informe técnico creado como resultado de A3.7 incluyendo qué modificaciones deben introducir en su código fuente para eliminar los posibles errores y malos olores, y para mejorar la complejidad ciclomática en aquellas clases con un valor más alto. Implemente esas modificaciones y realice análisis adicionales con SonarCloud, incluyendo el informe resultante de la versión modificada en la discusión del informe técnico.

**Comment by pabsanper** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/psg2-2122-g4-42-623308a4186c100016aa5edf/issues/gii-is-psg2/psg2-2122-g4-42/61?planning-poker) with ZenHub @diegonqui @marsamber @marsannar2 @pabparmen
