### ISSUE TITLE
Tarea 052 (EXTRA): Épicas en GitFlow

### ISSUE THREAD

**Issue by marsamber** [gii-is-psg2/psg2-2122-g4-42#62]
Como grupo, cree un apéndice en el informe técnico creado como resultado de A3.6 para describir la política utilizada para integrar el uso de épicas en la metodología de bifurcación de GitFlow. Entre las opciones disponibles para dicha integración están:
- Usar ramas para epics de la misma manera que se usaron para cualquier otro tema/tarea.
- Use ramas solo para los problemas/tareas concretos que pertenecen a las épicas, pero no la épica en sí.
- Aplicar el enfoque propuesto  [aquí](https://give.gitbook.io/development-manual/product-development/epics/epic-branches).
Los grupos deben especificar su elección y proporcionar una justificación que la justifique en dicho apéndice.

**Comment by pabsanper** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/psg2-2122-g4-42-623308a4186c100016aa5edf/issues/gii-is-psg2/psg2-2122-g4-42/62?planning-poker) with ZenHub @diegonqui @marsamber @marsannar2 @pabparmen
