### ISSUE TITLE
Tarea 053 (EXTRA): Seguir buenas prácticas

### ISSUE THREAD

**Issue by marsamber** [gii-is-psg2/psg2-2122-g4-42#63]
Como grupo, siga las mejores prácticas de equipo introducidas en S1 y S2 (especialmente en la relación entre las sucursales y la gestión de tareas) a lo largo del Sprint 3.

**Comment by pabsanper** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/psg2-2122-g4-42-623308a4186c100016aa5edf/issues/gii-is-psg2/psg2-2122-g4-42/63?planning-poker) with ZenHub @diegonqui @marsamber @marsannar2 @pabparmen
